<?php
/**
 * AURIONIX WEBSITE CONFIGURATION
 * This file is auto-generated by the installer
 * Place in root directory (public_html/)
 */

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_USERNAME', 'your_db_username');
define('DB_PASSWORD', 'your_db_password');
define('DB_NAME', 'aurionix_db');

// Site Configuration
define('SITE_URL', 'https://' . $_SERVER['HTTP_HOST']);
define('ADMIN_PATH', '/admin');
define('UPLOAD_PATH', '/uploads/');

// Security
define('SESSION_NAME', 'aurionix_session');
session_name(SESSION_NAME);
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

// Database Connection
try {
    $pdo = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USERNAME, DB_PASSWORD);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
} catch(PDOException $e) {
    die('Database connection failed: ' . $e->getMessage());
}

// Helper Functions
function getSetting($key, $default = '') {
    global $pdo;
    $stmt = $pdo->prepare("SELECT setting_value FROM settings WHERE setting_key = ?");
    $stmt->execute([$key]);
    $result = $stmt->fetch();
    return $result ? $result['setting_value'] : $default;
}

function updateSetting($key, $value) {
    global $pdo;
    $stmt = $pdo->prepare("INSERT INTO settings (setting_key, setting_value) VALUES (?, ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
    return $stmt->execute([$key, $value]);
}

function isLoggedIn() {
    return isset($_SESSION['user_id']) && isset($_SESSION['role']);
}

function isAdmin() {
    return isLoggedIn() && $_SESSION['role'] === 'admin';
}

function requireAdmin() {
    if (!isAdmin()) {
        header('Location: /admin/login.php');
        exit;
    }
}

function getUserCountry() {
    // Simple IP-based country detection
    $ip = $_SERVER['REMOTE_ADDR'];
    if ($ip === '127.0.0.1' || $ip === '::1') {
        return 'US'; // Default for localhost
    }
    
    // Use a free IP geolocation service
    $country = @file_get_contents("http://ip-api.com/json/{$ip}?fields=countryCode");
    if ($country) {
        $data = json_decode($country, true);
        return $data['countryCode'] ?? 'US';
    }
    return 'US'; // Default fallback
}

function getStreamingLink($albumId, $platform, $country = null) {
    global $pdo;
    if (!$country) $country = getUserCountry();
    
    // Try to get country-specific link first
    $stmt = $pdo->prepare("SELECT * FROM streaming_links WHERE album_id = ? AND platform = ? AND (country_code = ? OR country_code = 'global') ORDER BY country_code = ? DESC LIMIT 1");
    $stmt->execute([$albumId, $platform, $country, $country]);
    return $stmt->fetch();
}

function sanitizeInput($input) {
    return htmlspecialchars(trim($input), ENT_QUOTES, 'UTF-8');
}

function generateSlug($text) {
    return strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $text), '-'));
}

function formatDuration($seconds) {
    $minutes = floor($seconds / 60);
    $seconds = $seconds % 60;
    return sprintf('%d:%02d', $minutes, $seconds);
}

// Error Reporting (disable in production)
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Timezone
date_default_timezone_set('UTC');
?>